first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from main import views

urlpatterns = [
      url ('downvote/',views.downvote),
      url ('upvote/',views.upvote),
      url('answer/',views.answer),
      url('question/',views.question),
      url('dashboard/',views.dashboard),
      url('login/',views.login),
      url('signup/',views.signup),
       url('test/',views.test),
       url('',views.homePageView),

#url('hello/',views.hello,name='hello'),
#url('',views.homePageView,name='home'),

]

main/models.py
from django.core.validators import MaxValueValidator,MinValueValidator,EmailValidator
from django.db import models

class User(models.Model):
	name=models.CharField(max_length=100)
	age=models.IntegerField(blank=True,null=True,validators=[MaxValueValidator(150),MinValueValidator(0)])
	email=models.CharField(max_length=256,validators=[EmailValidator],null=True,unique=True)
	password=models.CharField(max_length=6,default="111222")
	GENDERS=(
		('F','Female'),
		('M','Male')
          )
	gender=models.CharField(max_length=1,choices=GENDERS)
	def __str__(self):
		return self.name

class Question(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	name=models.TextField(null=False)
	
	def __str__(self):
		return self.name

class Answer(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	question=models.ForeignKey(Question,on_delete=models.CASCADE)
	answer=models.TextField(null=False)
	upvotes=models.IntegerField(null=True,default= 0)
	downvotes=models.IntegerField(null=True,default = 0)
	# def __str__(self):
	# 	return self.answer

						
		
		
	

main/forms.py
from django import forms

from . import models
class UserForm(forms.ModelForm):
   class Meta:
   	model=models.User
   	fields= '__all__'

class UserLoginForm(forms.ModelForm):
   class Meta:
   	model=models.User
   	fields= ['email','password']

class QuestionForm(forms.ModelForm):
	class Meta:
		model=models.Question
		fields= ['name']

class AnswerForm(forms.ModelForm):
	class Meta:
		model=models.Answer
		fields=['answer','upvotes','downvotes']
						

main/views.py
from django.shortcuts import render
from django.http import HttpResponse ,HttpResponseRedirect
from . import forms
from main.models import User, Question ,Answer

# Create your views here.
def homePageView(request):
	return HttpResponse("hello world")

def test(request):
	return render(request,'test.html',{})

def signup(request):
	if request.method =='GET':
		form =forms.UserForm()
	else :
		form = forms.UserForm(request.POST)
		if  form.is_valid():
			objects=form.save()
			return HttpResponse("Form submitted Sucessfully")


	context = { 
	            'user_form': form
	}
	return render(request,'signup.html',context)

def dashboard(request):
		user_id=request.GET.get("user_id")
		user=User.objects.filter(id=user_id)
		questions=Question.objects.all
		print(questions)
		context= {
		"user" : user[0],
		"questions": questions
		}
		return render(request,'dashboard.html',context)
	
def login(request):
	if request.method =='GET':
		form =forms.UserLoginForm()
		context = {"UserLoginForm": form}
		return render(request,"ulogin.html",context)

	else :
		form = forms.UserLoginForm(request.POST)
		email=form.data["email"]
		password= form.data["password"]
		print( email,password)
		user=User.objects.filter(email=email ,password=password)
		print(user)
		if len(user)> 0:
			return HttpResponseRedirect('/dashboard/?user_id=' + str(user[0].id))
			#return HttpResponse(" Sucessfully login")
		
		else:
			context={"UserLoginForm": form}
			return render(request,'ulogin.html',context)


def question(request):
	if request.method =='GET':
		user_id=request.GET.get("user_id")
		form =forms.QuestionForm()
		context={
		      'question_form':form,
		      'user_id': user_id
		}
		return render(request,'question.html',context)
	else :
		form = forms.QuestionForm(request.POST)
		if form.is_valid():
			objects = form.save(commit= False)
			print("\n\n\nthis is user id \n\n",form.data["user_id"])
			user=User.objects.filter(id=form.data["user_id"])[0]
			objects.user = user
			objects.save()
			return HttpResponseRedirect('/dashboard/?user_id=' + str(form.data["user_id"]))

	

def answer(request):
		if request.method =='GET':

			user_id=request.GET.get("user_id")
			question_id = request.GET.get("question_id")
			form =forms.AnswerForm()
			context={'AnswerForm': form,'user_id' :user_id,'question_id': question_id }
			return render(request,'answer.html',context)
		else :
			form = forms.AnswerForm(request.POST)
			if form.is_valid():
				objects = form.save(commit=False)
				print("\n\n\n this is user id \n\n",form.data["user_id"])
				user=User.objects.filter(id=form.data["user_id"])[0]
				print(user)
				objects.user = user
				print(form.data)
				question_id = form.data["question_id"]
				print(question_id)
				objects.question_id= question_id
				objects.save()
			return HttpResponseRedirect('/dashboard/?user_id='+str(form.data["user_id"]))
def upvote(request):
	user_id=request.GET.get("user_id")
	answer_id=request.GET.get("answer_id")
	answer=Answer.objects.get(id=answer_id)
	upvotes=answer.upvotes
	answer.upvotes=upvotes+1
	answer.save()
	return HttpResponseRedirect('/dashboard/?user_id='+str(user_id))

def downvote(request):
	user_id=request.GET.get("user_id")
	answer_id=request.GET.get("answer_id")
	answer=Answer.objects.get(id=answer_id)
	downvotes=answer.downvotes
	answer.downvotes=downvotes+1
	answer.save()
	return HttpResponseRedirect('/dashboard/?user_id='+str(user_id))

					



					

			

	 
	

main/templates/answer.html
<!DOCTYPE html>
<html>  
    <head>
        </head>
        <body>
           <b> AnswerForm </b>
           <br>
           <br>
           <form action="" method = "POST">
           	     {%  csrf_token  %}
                 <input type="hidden" name ="user_id" value={{user_id}}>
                 <input type="hidden" name ="question_id" value={{question_id}}>
                 


           	    {{ AnswerForm.as_p }}
           	    <button type ="submit  answer">Submit</button>
           	</form>
            </body>
    </html>

main/templates/dashboard.html
<!DOCTYPE html>
<html>  
    <head>
        </head>
        <body>
           <b>Hello{{user.name}} welcome to Question and Answer</b>
           

           <b>ADD QUESTION</b><a href="/question/?user_id= {{ user.id  }}">Add Question</a>
           <br>
           <b>My Ques</b> <a href= "/question/?user_id={{user.id}}">Add Question</a>
           {% for question in questions %}
               <br>
               <br>
               <span>{{question.id}}</span> <span>{{question.name}}</span> -by {{question.user.id}}<span> <a href= "/answer/?user_id={{user.id}}&question_id={{question.id}}">Add Answer</a></span> 
              <ul>
               	{% for answer in question.answer_set.all %}
               	       <br>
               	       <li><span>{{answer.id}}</span>
               	       	<span>{{answer.answer}}</span>Answered by 
               	       	<span>{{user.name}}</span>  </li>               
               	       	 <li> <span>{{answer.upvotes}}</span>
               	       <span><a href="/upvote/?user_id={{ user.id }}&answer_id={{ answer.id }}"><button type=  "UPVOTE">Upvote</button></a></span>
               	       <span> {{answer.downvotes}} </span>
               	 <span><a href="/downvote/?user_id={{user.id}}&answer_id={{ answer.id }}"><button type=  "DOWNVOTE">Downvotes</button></a></span></li>
               	 {% endfor %} 
               	 </ul> 
               	 {%  endfor %}    
               	  </body>
    </html>

main/templates/hello.html
<!DOCTYPE html>
<html>  
    <head>
        </head>
        <body>
            This is my first web page
            </body>
    </html>

main/templates/login.html
22<!DOCTYPE html>
<html>  
    
        <body>
        	<form>
        		<input type="text" name="name" id="name" placeholder="name">
        		<br>
        		<br>
        		<input type="number" name="username_or_email"id="username_or_email" placeholder="age">
        		br
        		<input type="text" name="email"id="email" placeholder="email">
        		<br>
        		<br>
        		<label>Password : </label>
        		<input type="password" name="password" id=" password " placeholder="password">
        		<br>
        		<br>
        		<label>Gender  : </label>
        		<select name="gender" id="gender">
        			<option value = "M">Male</option>
        			<option value = "F">Female</option>
        		</select>
            </form>
            </body>
    </html>

main/templates/question.html
<!DOCTYPE html>
<html>  
    <head>
        </head>
        <body>
           <b>  QuestionForm</b>
           <br>
           <br>
           <form action="" method = "POST">
           	     {%  csrf_token  %}
                 <input type="hidden" name="user_id", value={{ user_id }}>
           	    {{ question_form.as_p }}
           	    <button type ="submit question">Submit</button>
           	</form>
            </body>
    </html>   

main/templates/signup.html
<!DOCTYPE html>
<html>  
    <head>
        </head>
        <body>
           <b> Sign Up Form</b>
           <br>
           <br>
           <form action="" method = "POST">
           	     {%  csrf_token  %}

           	    {{ user_form.as_p }}
           	    <button type ="submit">Submit</button>
           	</form>
            </body>
    </html>

main/templates/test.html
<!DOCTYPE html>
<html>  
    
        <body>
        	<form>
        		<input type="text" name="name" id="name" placeholder="name">
        		<br>
        		<br>
        		<input type="number" name="username_or_email"id="username_or_email" placeholder="age">
        		br
        		<input type="text" name="email"id="email" placeholder="email">
        		<br>
        		<br>
        		<label>Password : </label>
        		<input type="password" name="password" id=" password " placeholder="password">
        		<br>
        		<br>
        		<label>Gender  : </label>
        		<select name="gender" id="gender">
        			<option value = "M">Male</option>
        			<option value = "F">Female</option>
        		</select>
            </form>
            </body>
    </html>

main/templates/ulogin.html
   </head>
        <body>
           <b> Userlogin Form</b>
           <br>
           <br>
           <form action="" method = "POST">
           	     {%  csrf_token  %}

           	    {{ UserLoginForm.as_p }}
           	    <button type ="submit">Submit</button>
           	</form>
            </body>
    </html>